"""
Export representative training samples from the Kaggle 'sea-animals-image-dataste'
dataset into the frontend's public folder, so the species detail view can show
the imagery the computer-vision model was actually trained on.

Why this exists:
  The Kaggle dataset lives in ~/.cache/kagglehub (outside the Next.js build).
  next/image can only serve files from frontend/public, so we copy a small,
  optimised selection across at build/dev time.

Usage:
  python export_species_samples.py [--per-class 3]

Output:
  frontend/public/species/samples/<app-species-id>-<n>.webp
  frontend/src/data/species-samples.json   (manifest consumed by the UI)
"""
import os, json, glob, argparse
import numpy as np
from PIL import Image

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_PATH = r"C:\Users\Lenovo\.cache\kagglehub\datasets\vencerlanz09\sea-animals-image-dataste\versions\5"
LABEL_MAP_PATH = os.path.join(BASE_DIR, "species_label_map.json")
SPECIES_JSON_PATH = os.path.join(BASE_DIR, "..", "frontend", "src", "data", "species.json.ts")
OUT_DIR = os.path.join(BASE_DIR, "..", "frontend", "public", "species", "samples")
MANIFEST_PATH = os.path.join(BASE_DIR, "..", "frontend", "src", "data", "species-samples.json")

THUMB = (512, 288)  # 16:9 to match the SpeciesCard hero aspect ratio
MAX_SCAN_PER_CLASS = 200


def parse_species_json(path):
    """Extract id/name pairs from the TypeScript species data file."""
    import re
    text = open(path, encoding="utf-8").read()
    ids = re.findall(r'id:\s*"(sp-\d+)"', text)
    names = re.findall(r'name:\s*"([^"]+)"', text)
    return dict(zip(ids, names))


def crop_to_aspect(img, target_ratio):
    """Centre-crop so the image matches the 16:9 hero box without distortion."""
    w, h = img.size
    if w / h > target_ratio:
        new_w = int(h * target_ratio)
        left = (w - new_w) // 2
        return img.crop((left, 0, left + new_w, h))
    new_h = int(w / target_ratio)
    top = (h - new_h) // 2
    return img.crop((0, top, w, top + new_h))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-class", type=int, default=3,
                    help="How many sample images to export per Kaggle class")
    args = ap.parse_args()

    if not os.path.isdir(DATASET_PATH):
        raise SystemExit(f"Dataset not found at {DATASET_PATH}. Run download_sea_animals.py first.")

    label_map = json.load(open(LABEL_MAP_PATH, encoding="utf-8"))
    class_to_species = label_map["classToSpecies"]
    species_names = parse_species_json(SPECIES_JSON_PATH)

    os.makedirs(OUT_DIR, exist_ok=True)

    # species id -> list of web paths
    samples = {}
    skipped = []

    for cls_name in sorted(os.listdir(DATASET_PATH)):
        folder = os.path.join(DATASET_PATH, cls_name)
        if not os.path.isdir(folder):
            continue

        species_ids = class_to_species.get(cls_name, [])
        if not species_ids:
            skipped.append(cls_name)
            continue

        files = (glob.glob(os.path.join(folder, "*.jpg"))
                 + glob.glob(os.path.join(folder, "*.jpeg"))
                 + glob.glob(os.path.join(folder, "*.png")))
        files = sorted(files)[:MAX_SCAN_PER_CLASS]

        # Deterministic spread across the folder so samples are visually varied
        # rather than N near-duplicate frames from the same burst.
        if len(files) > args.per_class:
            step = len(files) / args.per_class
            picks = [files[int(i * step)] for i in range(args.per_class)]
        else:
            picks = files

        # The class maps to several app species; distribute the picks round-robin.
        for idx, src_path in enumerate(picks):
            sp_id = species_ids[idx % len(species_ids)]
            out_name = f"{sp_id}-{cls_name.lower().replace(' ', '-')}-{idx + 1}.webp"
            out_path = os.path.join(OUT_DIR, out_name)
            try:
                img = Image.open(src_path).convert("RGB")
                img = crop_to_aspect(img, 16 / 9)
                img = img.resize(THUMB, Image.LANCZOS)
                img.save(out_path, "WEBP", quality=72, method=6)
            except Exception as exc:
                print(f"  ! failed {src_path}: {exc}")
                continue

            samples.setdefault(sp_id, []).append(f"/species/samples/{out_name}")

    # Stable ordering + de-duplicate
    samples = {k: sorted(set(v)) for k, v in sorted(samples.items())}

    manifest = {
        "_meta": {
            "description": "Representative training images from the Kaggle sea-animals dataset, exported for UI display.",
            "dataset": label_map["_meta"]["dataset"],
            "perClass": args.per_class,
            "note": "Generated by ml/export_species_samples.py - do not edit by hand.",
        },
        "samples": samples,
        "coveredSpecies": sorted(samples.keys()),
        "uncoveredSpecies": sorted(set(species_names) - set(samples.keys())),
        "unmappedClasses": sorted(skipped),
    }
    with open(MANIFEST_PATH, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    total = sum(len(v) for v in samples.values())
    print(f"Exported {total} sample images for {len(samples)} species -> {OUT_DIR}")
    print(f"Manifest: {MANIFEST_PATH}")
    print(f"Species without dataset coverage: {manifest['uncoveredSpecies']}")
    for sp_id, paths in samples.items():
        print(f"  {sp_id} {species_names.get(sp_id, '?')}: {len(paths)}")


if __name__ == "__main__":
    main()