/**
 * Automated Incident Report service (Step 4).
 * ============================================================
 * Assembles an evidence-backed, incident-specific report for ONE completed
 * `drone_inspections` record from real persisted data only:
 *
 *   inspection → alert → sensor → trigger reading → evidence
 *
 * Rules:
 *   - No invented values, timestamps, detections, readings, or GPS coords.
 *   - Anything not persisted is omitted or explicitly marked unavailable.
 *   - One snapshot row per inspection (UNIQUE inspection_id → idempotent).
 *
 * Query budget per report: 1 inspection + 1 alert + 1 sensor + 1 reading +
 * 1 evidence query (no N+1).
 */

import { getDb } from "../db";

export class InspectionNotFoundError extends Error {
  constructor(inspectionId: string) {
    super(`Inspection '${inspectionId}' not found.`);
    this.name = "InspectionNotFoundError";
  }
}

export class InspectionIncompleteError extends Error {
  constructor(inspectionId: string, phase: string) {
    super(`Inspection '${inspectionId}' is '${phase}', not complete — no final report yet.`);
    this.name = "InspectionIncompleteError";
  }
}

export interface ReportEvidenceItem {
  id: string;
  kind: string;
  label: string;
  /** Raw persisted confidence (fraction like 0.91, or percent like 97.7). */
  confidence: number | null;
  /** Normalized human display, e.g. "91%" — never "9100%". */
  confidenceDisplay: string;
  detail: string | null;
  capturedAt: string;
  /** Frame this evidence was derived from (null when not frame-linked). */
  frameId: string | null;
  /** Provenance of the frame/evidence (null for pre-vision rows). */
  sourceType: string | null;
}

export interface ReportTimelineEntry {
  timestamp: string;
  event: string;
  description: string;
}

export interface IncidentReport {
  reportId: string;
  inspectionId: string;
  generatedAt: string;
  generatedBy: string | null;
  incident: {
    title: string;
    status: string;
    severity: string | null;
    alertId: string | null;
    detectedAt: string | null;
    location: string | null;
    latitude: number | null;
    longitude: number | null;
    sensorId: string | null;
    sensorName: string | null;
    /** Provenance of the incident telemetry (null = recorded before sourcing). */
    dataSource: string | null;
    deviceId: string | null;
  };
  detection: {
    alertType: string | null;
    category: string | null;
    message: string | null;
    relatedEntity: string | null;
    /** Parsed from the persisted inspection summary when present, else null. */
    anomalyScore: number | null;
    detectionLatencyMs: number | null;
    triggerReading: {
      temperature: number | null;
      ph: number | null;
      salinity: number | null;
      oxygen: number | null;
      turbidity: number | null;
      recordedAt: string | null;
    } | null;
  };
  sensorReadings: {
    temperature: number | null;
    ph: number | null;
    salinity: number | null;
    oxygen: number | null;
    turbidity: number | null;
    recordedAt: string | null;
  } | null;
  response: {
    droneId: string | null;
    droneName: string | null;
    selectionReason: string | null;
    distanceKm: number | null;
    etaSeconds: number | null;
    origin: { lat: number | null; lng: number | null };
    target: { lat: number | null; lng: number | null };
    dispatchedAt: string | null;
    /** No arrived_at column is persisted — never fabricated. */
    arrivalAt: null;
    arrivalNote: string;
    completedAt: string | null;
  };
  inspection: {
    inspectionId: string;
    phase: string;
    startedAt: string | null;
    completedAt: string | null;
    durationSeconds: number | null;
    summary: string | null;
    findings: { kind: string; label: string; confidence: number | null; detail: string | null }[];
  };
  evidence: ReportEvidenceItem[];
  timeline: ReportTimelineEntry[];
  vision: {
    sourceType: string | null;
    cameraId: string | null;
    framesCaptured: number;
    framesProcessed: number;
    framesDropped: number;
    representativeFrameId: string | null;
  };
  finalAssessment: {
    severity: string | null;
    threatCount: number;
    summary: string | null;
    assessment: string;
  };
  disclosure: string;
}

const DISCLOSURE_TEXT =
  "This incident was generated by the DeepSea Guardian controlled software demonstration. " +
  "Sensor input and drone movement are simulated. Camera frames are sample frames. " +
  "AI inference is real resident model inference (Isolation Forest anomaly detection " +
  "and MobileNet species classification) executed by the project's own pipeline. " +
  "Vision input provenance is recorded per frame. During software-only validation, " +
  "frames may originate from deterministic test fixtures. Physical underwater " +
  "camera/ROV validation is not implied unless a hardware source is explicitly " +
  "connected and reports hardware provenance.";

const numOrNull = (v: unknown): number | null =>
  typeof v === "number" && Number.isFinite(v) ? v : null;

const strOrNull = (v: unknown): string | null =>
  typeof v === "string" && v.length > 0 ? v : null;

/**
 * Normalize persisted confidence to a display string.
 * Stored values are fractions (0.91) or percents (97.7) depending on source.
 */
export function formatConfidence(raw: unknown): { value: number | null; display: string } {
  const n = numOrNull(raw);
  if (n === null) return { value: null, display: "n/a" };
  const pct = n > 1 ? n : n * 100;
  return { value: n, display: `${Math.round(pct)}%` };
}

function durationSeconds(startedAt: string | null, completedAt: string | null): number | null {
  if (!startedAt || !completedAt) return null;
  const ms = Date.parse(completedAt) - Date.parse(startedAt);
  if (!Number.isFinite(ms) || ms < 0) return null;
  return Math.round(ms / 1000);
}

/** Anomaly score is persisted inside the inspection summary string — extract it honestly, else null. */
function extractAnomalyScore(summary: string | null): number | null {
  if (!summary) return null;
  const m = summary.match(/ML anomaly score ([\d.]+)/);
  if (!m) return null;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : null;
}

/**
 * Load-or-generate the incident report snapshot for a completed inspection.
 * Idempotent: a second call returns the already-persisted snapshot.
 */
export function getOrCreateIncidentReport(
  inspectionId: string,
  generatedBy: string | null = null
): { report: IncidentReport; created: boolean } {
  const db = getDb();

  // ── 0. Idempotency: return the persisted snapshot if it exists ─────────────
  const existing = db.prepare(
    "SELECT report_json FROM incident_reports WHERE inspection_id = ?"
  ).get(inspectionId) as any;
  if (existing?.report_json) {
    return { report: JSON.parse(existing.report_json) as IncidentReport, created: false };
  }

  // ── 1. Inspection (must exist and be complete) ──────────────────────────────
  const inspection = db.prepare("SELECT * FROM drone_inspections WHERE id = ?").get(inspectionId) as any;
  if (!inspection) throw new InspectionNotFoundError(inspectionId);
  if (inspection.phase !== "complete") throw new InspectionIncompleteError(inspectionId, inspection.phase);

  // ── 2. Alert (via persisted link) ───────────────────────────────────────────
  const alert = inspection.alert_id
    ? (db.prepare("SELECT * FROM alerts WHERE id = ?").get(inspection.alert_id) as any)
    : null;

  // ── 3. Sensor ───────────────────────────────────────────────────────────────
  const sensor = inspection.sensor_id
    ? (db.prepare("SELECT * FROM sensors WHERE id = ?").get(inspection.sensor_id) as any)
    : null;

  // ── 4. Trigger reading: closest persisted reading to the alert timestamp ────
  let reading: any = null;
  const referenceTs = alert?.timestamp ?? inspection.started_at;
  if (inspection.sensor_id && referenceTs) {
    reading = db.prepare(
      `SELECT sensor_id, ph, temp, salinity, oxygen, turbidity, recorded_at, source, device_id
       FROM sensor_readings
       WHERE sensor_id = ?
       ORDER BY ABS(strftime('%s', recorded_at) - strftime('%s', ?))
       LIMIT 1`
    ).get(inspection.sensor_id, referenceTs) as any;
  }
  // Provenance of the incident data (Phase 6B): the closest reading that
  // carries source metadata — REAL HARDWARE vs simulated vs manual.
  const provenance = reading?.source
    ? { source: reading.source, deviceId: reading.device_id ?? null }
    : null;

  // ── 5. Evidence (chronological) + persisted AI findings ─────────────────────
  const evidenceRows = (db.prepare(
    `SELECT id, kind, label, confidence, detail, captured_at, frame_id, source_type
     FROM inspection_evidence
     WHERE inspection_id = ?
     ORDER BY captured_at ASC`
  ).all(inspectionId) as any[]) ?? [];

  let threatFindings: { kind: string; label: string; confidence: number | null; detail: string | null }[] = [];
  try {
    const parsed = JSON.parse(inspection.threat_json ?? "[]");
    if (Array.isArray(parsed)) {
      threatFindings = parsed.map((f: any) => ({
        kind: strOrNull(f?.kind) ?? "unknown",
        label: strOrNull(f?.label) ?? "Unknown finding",
        confidence: numOrNull(f?.confidence),
        detail: strOrNull(f?.detail),
      }));
    }
  } catch { /* malformed threat_json → empty findings, evidence still shown */ }

  // ── Assemble ────────────────────────────────────────────────────────────────
  const generatedAt = new Date().toISOString();
  const anomalyScore = extractAnomalyScore(inspection.summary);
  const duration = durationSeconds(inspection.started_at, inspection.completed_at);
  const threatCount = threatFindings.length > 0 ? threatFindings.length : evidenceRows.length;

  const evidence: ReportEvidenceItem[] = evidenceRows.map((e) => {
    const c = formatConfidence(e.confidence);
    return {
      id: e.id,
      kind: strOrNull(e.kind) ?? "unknown",
      label: strOrNull(e.label) ?? "Unknown evidence",
      confidence: c.value,
      confidenceDisplay: c.display,
      detail: strOrNull(e.detail),
      capturedAt: e.captured_at,
      frameId: strOrNull(e.frame_id),
      sourceType: strOrNull(e.source_type),
    };
  });

  // ── 5b. Vision provenance: frame rows captured for this inspection ─────────
  // Counts come from persisted vision_frames rows (never invented). Frames
  // captured but dropped/failed are counted honestly from processing_status.
  let vision = {
    sourceType: null as string | null,
    cameraId: null as string | null,
    framesCaptured: 0,
    framesProcessed: 0,
    framesDropped: 0,
    representativeFrameId: null as string | null,
  };
  try {
    const frameRows = (db.prepare(
      `SELECT id, source_type, camera_id, processing_status
       FROM vision_frames WHERE inspection_id = ? ORDER BY captured_at ASC`
    ).all(inspectionId) as any[]) ?? [];
    if (frameRows.length > 0) {
      vision = {
        sourceType: strOrNull(frameRows[0].source_type),
        cameraId: strOrNull(frameRows[0].camera_id),
        framesCaptured: frameRows.length,
        framesProcessed: frameRows.filter((f) => f.processing_status === "PROCESSED").length,
        framesDropped: frameRows.filter((f) => f.processing_status === "DROPPED").length,
        representativeFrameId: strOrNull(evidence.find((e) => e.frameId)?.frameId),
      };
    }
  } catch { /* vision block stays empty */ }

  const readingBlock = reading
    ? {
        temperature: numOrNull(reading.temp),
        ph: numOrNull(reading.ph),
        salinity: numOrNull(reading.salinity),
        oxygen: numOrNull(reading.oxygen),
        turbidity: numOrNull(reading.turbidity),
        recordedAt: strOrNull(reading.recorded_at),
      }
    : null;

  const timeline: ReportTimelineEntry[] = [];
  if (readingBlock?.recordedAt) {
    timeline.push({
      timestamp: readingBlock.recordedAt,
      event: "Anomalous sensor reading recorded",
      description: `Sensor ${inspection.sensor_name ?? inspection.sensor_id} captured the trigger reading.`,
    });
  }
  if (alert) {
    timeline.push({
      timestamp: alert.timestamp,
      event: "Anomaly detected",
      description: `Isolation Forest inference flagged an anomaly at ${alert.location ?? inspection.sensor_name}.`,
    });
    timeline.push({
      timestamp: alert.timestamp,
      event: "Alert generated",
      description: `${String(alert.type ?? "critical").toUpperCase()} alert recorded (${alert.category ?? "pollution"}).`,
    });
  }
  if (inspection.started_at) {
    timeline.push({
      timestamp: inspection.started_at,
      event: "Drone dispatched",
      description: `${inspection.drone_name} dispatched to ${inspection.sensor_name} (${inspection.selection_reason ?? "autonomous selection"}).`,
    });
  }
  // NOTE: no arrived_at column is persisted, so arrival is intentionally absent
  // from the timeline rather than fabricated.
  const firstEvidence = evidence[0];
  if (firstEvidence) {
    timeline.push({
      timestamp: firstEvidence.capturedAt,
      event: "Evidence captured",
      description: `${evidence.length} evidence item(s) recorded during on-site inspection.`,
    });
  }
  if (inspection.completed_at) {
    timeline.push({
      timestamp: inspection.completed_at,
      event: "Inspection completed",
      description: `Severity classified as ${inspection.severity ?? "unknown"}; ${threatCount} threat(s) identified.`,
    });
  }
  timeline.push({
    timestamp: generatedAt,
    event: "Report generated",
    description: "Automated incident report assembled from persisted pipeline records.",
  });

  const assessment =
    `Autonomous response to the ${alert?.type ?? "critical"} anomaly at ${inspection.sensor_name ?? "unknown location"} ` +
    `completed in ${duration !== null ? `${duration}s` : "an unrecorded duration"} with severity ${inspection.severity ?? "unknown"} ` +
    `and ${threatCount} recorded threat(s). Drone ${inspection.drone_name ?? "unknown"} executed the full ` +
    `detect → alert → dispatch → inspect → evidence chain with ${evidence.length} persisted evidence item(s).`;

  const report: IncidentReport = {
    reportId: `INC-${inspection.id}`,
    inspectionId: inspection.id,
    generatedAt,
    generatedBy,
    incident: {
      title: `${strOrNull(alert?.category) === "pollution" || !alert ? "Chemical / Marine Pollution Event" : "Ocean Anomaly Event"} — ${inspection.sensor_name ?? "Unknown location"}`,
      status: "complete",
      severity: strOrNull(inspection.severity),
      alertId: strOrNull(inspection.alert_id),
      detectedAt: strOrNull(alert?.timestamp),
      location: strOrNull(alert?.location) ?? strOrNull(inspection.sensor_name),
      latitude: sensor ? numOrNull(sensor.lat) : numOrNull(inspection.target_lat),
      longitude: sensor ? numOrNull(sensor.lng) : numOrNull(inspection.target_lng),
      sensorId: strOrNull(inspection.sensor_id),
      sensorName: strOrNull(inspection.sensor_name),
      dataSource: provenance?.source ?? null,
      deviceId: provenance?.deviceId ?? null,
    },
    detection: {
      alertType: strOrNull(alert?.type),
      category: strOrNull(alert?.category),
      message: strOrNull(alert?.message),
      relatedEntity: strOrNull(alert?.related_entity),
      anomalyScore,
      detectionLatencyMs: null, // not persisted by the pipeline — honestly unavailable
      triggerReading: readingBlock,
    },
    sensorReadings: readingBlock,
    response: {
      droneId: strOrNull(inspection.drone_id),
      droneName: strOrNull(inspection.drone_name),
      selectionReason: strOrNull(inspection.selection_reason),
      distanceKm: numOrNull(inspection.distance_km),
      etaSeconds: numOrNull(inspection.eta_seconds),
      origin: { lat: numOrNull(inspection.origin_lat), lng: numOrNull(inspection.origin_lng) },
      target: { lat: numOrNull(inspection.target_lat), lng: numOrNull(inspection.target_lng) },
      dispatchedAt: strOrNull(inspection.started_at),
      arrivalAt: null,
      arrivalNote: "Recorded in live mission timeline",
      completedAt: strOrNull(inspection.completed_at),
    },
    inspection: {
      inspectionId: inspection.id,
      phase: inspection.phase,
      startedAt: strOrNull(inspection.started_at),
      completedAt: strOrNull(inspection.completed_at),
      durationSeconds: duration,
      summary: strOrNull(inspection.summary),
      findings: threatFindings,
    },
    evidence,
    timeline,
    vision,
    finalAssessment: {
      severity: strOrNull(inspection.severity),
      threatCount,
      summary: strOrNull(inspection.summary),
      assessment,
    },
    disclosure: DISCLOSURE_TEXT,
  };

  // ── Persist snapshot (idempotent via UNIQUE inspection_id) ──────────────────
  db.prepare(
    `INSERT OR IGNORE INTO incident_reports
       (id, inspection_id, alert_id, severity, report_json, generated_at, generated_by)
     VALUES (?, ?, ?, ?, ?, ?, ?)`
  ).run(
    report.reportId,
    inspection.id,
    inspection.alert_id ?? null,
    inspection.severity ?? null,
    JSON.stringify(report),
    generatedAt,
    generatedBy
  );

  return { report, created: true };
}

/** List persisted incident snapshots (newest first) with optional filters. */
export function listIncidentReports(options: {
  limit?: number | string;
  severity?: string;
}): { reports: { reportId: string; inspectionId: string; severity: string | null; location: string | null; sensorName: string | null; generatedAt: string }[]; total: number } {
  const db = getDb();
  const limit = Math.min(Math.max(Number(options.limit) || 50, 1), 200);
  const allowedSeverities = ["critical", "high", "medium", "low"];
  const severity = allowedSeverities.includes(String(options.severity)) ? String(options.severity) : null;

  let query = `SELECT id, inspection_id, severity, report_json, generated_at FROM incident_reports WHERE 1=1`;
  const params: any[] = [];
  if (severity) {
    query += ` AND severity = ?`;
    params.push(severity);
  }
  query += ` ORDER BY generated_at DESC LIMIT ?`;
  params.push(limit);

  const rows = db.prepare(query).all(...params) as any[];
  const reports = rows.map((r) => {
    let parsed: any = null;
    try { parsed = JSON.parse(r.report_json); } catch { /* ignore */ }
    return {
      reportId: r.id,
      inspectionId: r.inspection_id,
      severity: r.severity,
      location: parsed?.incident?.location ?? null,
      sensorName: parsed?.incident?.sensorName ?? null,
      generatedAt: r.generated_at,
    };
  });
  return { reports, total: reports.length };
}
